# Generated by Django 5.0.4 on 2024-05-09 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='rg',
            field=models.CharField(default=0, max_length=12),
            preserve_default=False,
        ),
    ]
