# Generated by Django 5.0.4 on 2024-07-25 12:32

import django.contrib.auth.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('pessoa', '0003_alter_pessoa_rg'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pessoa',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelManagers(
            name='pessoa',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='cpf',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='id',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='nome',
        ),
        migrations.AddField(
            model_name='pessoa',
            name='usuario_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.usuario'),
            preserve_default=False,
        ),
    ]
